SET IDENTITY_INSERT [dbo].[Orders] ON
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (5, N'first order', CAST(17.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (6, N'second order', CAST(20.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (7, N'third order', CAST(17.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (8, N'test', CAST(10.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (9, N'last Order', CAST(25.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (10, N'order one', CAST(110.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (11, N'order two', CAST(35.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (12, N'order three', CAST(85.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (13, N'order four', CAST(90.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (14, N'order five', CAST(25.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (15, N'order six', CAST(15.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (16, N'order seven', CAST(15.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (17, N'order eight', CAST(45.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (18, N'order nine', CAST(75.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (19, N'order ten', CAST(30.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (20, N'order eleven', CAST(10.00 AS Decimal(18, 2)), 0)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (21, N'order thirteen', CAST(25.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Orders] ([OrderId], [OrderName], [Amount], [IsPaid]) VALUES (22, N'last test', CAST(115.00 AS Decimal(18, 2)), 0)
SET IDENTITY_INSERT [dbo].[Orders] OFF
